/* Autogenerated by png2wx.pl on Sun Jan 31 00:01:26 2021 */
#ifndef BITMAP_H
#define BITMAP_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_anote_icon128;
extern wxBitmap *_img_anote_icon16;

#endif /* BITMAP_H */
