/* Autogenerated by png2wx.pl on Fri Jan 29 22:00:11 2021 */
#ifndef BITMAP_H
#define BITMAP_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_anote_icon;

#endif /* BITMAP_H */
