name: build-linux

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install wheel conan

    - name: Install system libs
      run: |
        sudo apt-get update
        sudo apt-get install libgtk2.0-dev libgl1-mesa-dev
        sudo apt-get install libx11-dev
        sudo apt-get install libx11-xcb-dev
        sudo apt-get install libfontenc-dev
        sudo apt-get install libice-dev
        sudo apt-get install libsm-dev
        sudo apt-get install libxau-dev
        sudo apt-get install libxaw7-dev
        sudo apt-get install libxcomposite-dev
        sudo apt-get install libxcursor-dev
        sudo apt-get install libxdamage-dev
        sudo apt-get install libxdmcp-dev
        sudo apt-get install libxext-dev
        sudo apt-get install libxfixes-dev
        sudo apt-get install libxi-dev
        sudo apt-get install libxinerama-dev
        sudo apt-get install libxkbfile-dev
        sudo apt-get install libxmu-dev
        sudo apt-get install libxmuu-dev
        sudo apt-get install libxpm-dev
        sudo apt-get install libxrandr-dev
        sudo apt-get install libxrender-dev
        sudo apt-get install libxres-dev
        sudo apt-get install libxss-dev
        sudo apt-get install libxt-dev
        sudo apt-get install libxtst-dev
        sudo apt-get install libxv-dev
        sudo apt-get install libxvmc-dev
        sudo apt-get install libxxf86vm-dev
        sudo apt-get install xtrans-dev
        sudo apt-get install libxcb-render0-dev
        sudo apt-get install libxcb-render-util0-dev
        sudo apt-get install libxcb-xkb-dev
        sudo apt-get install libxcb-icccm4-dev
        sudo apt-get install libxcb-image0-dev
        sudo apt-get install libxcb-keysyms1-dev
        sudo apt-get install libxcb-randr0-dev
        sudo apt-get install libxcb-shape0-dev
        sudo apt-get install libxcb-sync-dev
        sudo apt-get install libxcb-xfixes0-dev
        sudo apt-get install libxcb-xinerama0-dev
        sudo apt-get install xkb-data
        sudo apt-get install libxcb-dri3-dev
        sudo apt-get install uuid-dev
        sudo apt-get install libxcb-util-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Install Conan Libraries
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        conan remote add gitlab https://gitlab.com/api/v4/packages/conan
        conan user gitlab+deploy-token-653038 -r gitlab -p sBwmejFz5Pn-gZPSNFMy
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan install ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: conan build ..

