name: build-Windows

#on:
#  release:
#    types: [created]

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install "conan>=2,<3"
        conan profile detect --force

    - name: Install Conan Libraries
      run: conan install . --build=missing -s build_type=${{ env.BUILD_TYPE }}

    - name: Build
      run: conan build . -s build_type=${{ env.BUILD_TYPE }}

#    - name: upload file
#      uses: xresloader/upload-to-github-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        file: "*.dmg;bin/*.dmg;*.app;"
#        tags: true
#        draft: true
#        verbose: true
